### ISSUE TITLE
Website Dimension "Stretched" Caused By Long Responses

### ISSUE THREAD

**Issue by LatiBlueLatios** [josephrocca/OpenCharacters#1]
Inputting a long response that does not go into a new line causes the page to increase in dimensions, specifically at the elongated response. 

## How to replicate 
Input a response like aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa *You get what I mean*

**Comment by josephrocca** [comment]
Thanks! Should be fixed now. (Allow a couple of minutes for Github Pages cache to clear)
