### ISSUE TITLE
Feature request: Add more / Continue response

### ISSUE THREAD

**Issue by Pawel-Dymek** [josephrocca/OpenCharacters#10]
Sometimes we don't need to regenerate the whole message, but we just need it to be a bit longer.

I think it would be cool to allow users to generate another response from the AI just below it's previous answer.

Or maybe some kind of button "add more" attached to the AI's response.

**Comment by josephrocca** [comment]
You can prompt the AI to reply again by typing `/ai`, but sometimes the AI may get confused and reply as the user if it has become accustomed to the back-and-forth pattern. Unfortunately with the chat-based 3.5-turbo there's no way to extend a message - so you have to add a new message. I hope OpenAI adds this ability at some point
