### ISSUE TITLE
Feature request: Reply as me

### ISSUE THREAD

**Issue by Pawel-Dymek** [josephrocca/OpenCharacters#11]
Maybe it's just me, and I'm lazy, but sometimes I'd just like to be able to press a button and watch how the conversation unfolds without me needing to do anything xD

I propose a feature that would allow AI to "roleplay" as me from each conversation.

**Comment by The-Acronyx** [comment]
PygmalionAI (possibly just ooogabooga’s version) has a feature called “Impersonate” which does exactly that.
