### ISSUE TITLE
Feature request: Send messages as System

### ISSUE THREAD

**Issue by Pawel-Dymek** [josephrocca/OpenCharacters#12]
It's great that we can setup characters with the system message. But as far as I know, there is currently no way to send system messages when you are already in an active conversation, right?

I think that the ability to send system messages anytime would work great as a "pointers" for AI into what direction take the conversation.

**Comment by josephrocca** [comment]
Hey @Pawel-Dymek this isn't well documented unfortunately, but to create a system message you just write `/sys <your message>`. Currently the slash commands are shown if you hover your cursor over the input box, but I'll think of a better way to inform users about this
