### ISSUE TITLE
Response delay?

### ISSUE THREAD

**Issue by egormly** [josephrocca/OpenCharacters#15]
I have chatGPT open in one window and this in another both using 3.5.  The responses take minutes to return vs seconds via OpenAI app.  I get that there is an interpreter involved, a middle man, but what can I do to speed it up, what is causing the delay, can I fix it?

**Comment by josephrocca** [comment]
Hi, sorry about this - is it happening consistently for you, or just every now and then? It definitely shouldn't be taking minutes. Should take a few seconds to respond.

**Comment by josephrocca** [comment]
@egormly are you still having this issue?

**Comment by josephrocca** [comment]
Please feel free to ping me or open another issue if this is still happening for you. Might have just been a temporary problem with the API - it's been happening fairly often: https://status.openai.com/
