### ISSUE TITLE
Starter characters scroll

### ISSUE THREAD

**Issue by jonathanchourio** [josephrocca/OpenCharacters#3]
when you add many starter characters no scroll down... i was trying to create many characters and adding to start but its not possible scrolldown only show : https://pasteboard.co/42v18BWKEwFY.png

**Comment by josephrocca** [comment]
Thanks! This should be fixed now - if not, let me know. (may take a minute or two for github cache to refresh - try clicking browser refresh a few times to clear cache if it's still an issue)
