### ISSUE TITLE
Cannot read properties of undefined (reading 'digest') at sha256Text

### ISSUE THREAD

**Issue by drusepth** [josephrocca/OpenCharacters#32]
I get this javascript alert after every message (as well as after refreshing the page on any chat where a message is loading):

![qecaLmN](https://user-images.githubusercontent.com/538235/231865351-1f13fad3-67b4-42cf-8764-6da6c154d0fe.png)

In the console, I also see this stack trace:

![2bYrEdl](https://user-images.githubusercontent.com/538235/231865773-4f4f3ca0-17d5-4427-b486-f5e53e4bd045.png)

> (index):3324 TypeError: Cannot read properties of undefined (reading 'digest')
>     at sha256Text (utils.js?v=23:342:42)
>     at countTokensInMessages ((index):1972:28)
>     at getBotReply ((index):2509:40)
>     at async doBotReplyIfNeeded ((index):3296:67)

The exact line throwing the error is
```js
const hashBuffer = await crypto.subtle.digest('SHA-256', msgUint8);
```

I'm not sure if this is perhaps just a setup issue on my part, so I've also included my setup instructions below.

# Setup details
I'm running the project zip from [the local setup doc](https://github.com/josephrocca/OpenCharacters/blob/main/docs/local-setup.md) locally and set my OpenAI key. I'm also serving the project with Apache instead of the Web Server for Chrome app, since I'm planning to host on a remote, headless server.

I'm pretty sure, according to [this documentation on `Crypto: subtle`](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle) that the problem is that I'm not serving the page over HTTPS and therefore `crypto.subtle` is unavailable. 

Just figured I'd open this issue (and hopefully close it shortly) while I dig in for myself and anyone else that sees this specific error in the future. :+1:

**Comment by drusepth** [comment]
Hurrah! Enabling HTTPS was enough to resolve this error, so I'll close this issue. Hopefully it's helpful for anyone searching for the same error in the future.

**Comment by josephrocca** [comment]
Thanks! Next version will have an informative failure message so that people know they need HTTPS.
