### ISSUE TITLE
Feature request: Insert messages / responses

### ISSUE THREAD

**Issue by Marko731** [josephrocca/OpenCharacters#40]
There's already a button to delete messages, but it would be possible to add an button to insert messages too? Ideally, there would be a dropdown in the insert message popup, allowing to select the role for the new message (User / System / AI).

**Comment by josephrocca** [comment]
Thanks! This is added. It's a hidden option in the "edit message" popup (pencil icon next to message author name). It opens a "sub-popup". Please let me know your use case if you use this often enough that you want a more ergonomic way to insert messages.

**Comment by Marko731** [comment]
Excellent, thanks very much! :D
