### ISSUE TITLE
AI instructions are omitted when generating variant responses

### ISSUE THREAD

**Issue by kickahaota** [josephrocca/OpenCharacters#42]
Currently, if you use `/ai instruction` to give the AI an instruction -- either on its own, or at the end of a normal user response -- the instruction is correctly reflected in the AI response. But if you then use the blue button to generate a variant of the response, the AI instruction is apparently not included in the new API call, and so is not reflected in the variant response.

(Thank you for this great project!)

**Comment by kickahaota** [comment]
I notice that the AI instruction for each message is now stored in the conversation history, and that variant responses now appear to reflect the AI instruction. Great stuff! I'll open another issue with a potential enhancement, but I'll close this one as fixed.

**Comment by josephrocca** [comment]
Ah, sorry - forgot to update this issue, thanks for the suggestion!
