### ISSUE TITLE
JS:Downloader-AQL [Trj] found when checking for Virustotal

### ISSUE THREAD

**Issue by ryancoolround** [josephrocca/OpenCharacters#43]
https://www.virustotal.com/gui/file/5692497e685b9c9f5a6866277a33ca37cbbdfa8771a26e1a33c97586f6a0d4b4?nocache=1

"JS:Downloader-AQL [Trj]" is a Trojan virus of the "downloader" type detected by antivirus software on a computer or device that operates on JavaScript (JS).

This type of virus typically infiltrates a device through a malicious website that can enter the computer when clicking a link or downloading a file. The downloader virus may download and execute other malicious programs on your device, which can behave unpredictably and affect the security of your data and personal information.

If your antivirus has detected "JS:Downloader-AQL [Trj]", it is recommended to immediately remove it using an antivirus program. It is also recommended to check the computer for other malware and to be more vigilant about internet security when using the device.

**Comment by josephrocca** [comment]
It's a false positive - OpenCharacters is just a html file. You can't put a virus in a HTML file - if you could, then simply clicking on a link / visiting a website could give you a virus. The only thing that this HTML file can "download" is the IndexedDB dump / thread export JSON files, and they're completely harmless (they're data files, not executable).
