### ISSUE TITLE
Generating a user reply failed

### ISSUE THREAD

**Issue by wind2sing** [josephrocca/OpenCharacters#46]
```javascript
TypeError: Cannot read properties of null (reading 'name')
    at doBotReplyInPlaceOfUser ((index):7082:48)
    at async HTMLButtonElement.sendButtonClickHandler ((index):5678:15)
```

<img width="836" alt="image" src="https://github.com/josephrocca/OpenCharacters/assets/66316949/972f4aed-e701-4f85-8ae4-25bf657c6fcb">

**Comment by josephrocca** [comment]
Ah, thanks! This should be fixed now. Please let me know if not.
