### ISSUE TITLE
Feature request: Include AI instruction in 'data used to generate this message' dialog

### ISSUE THREAD

**Issue by kickahaota** [josephrocca/OpenCharacters#48]
You recently enhanced OpenCharacters so that AI instructions (given using the `/ai` command) are saved in the conversation history.

Now that that's done, it would be nice if the AI instruction was included in the 'Here's some data that the character used to generate this message:' dialog that appears when you click on the brain icon next to an AI response.

Thanks again for the extremely useful project!

**Comment by josephrocca** [comment]
Thanks! Just added this
