### ISSUE TITLE
'Regenerate response' and 'message generation info' icons are shown and enabled for user's messages in chat

### ISSUE THREAD

**Issue by kickahaota** [josephrocca/OpenCharacters#55]
The AI is now offering to rewrite my stuff. :) The blue regenerate-response icon is now shown for all messages in the chat, not just the AI's messages. And sure enough, it works; if I click the icon on one of my messages, the AI happily writes an alternate response. I'm not sure that's intentional.

The pink-brain 'show message generation info' icon is also shown for all messages in the chat, not just the AI's.

**Comment by josephrocca** [comment]
Yep it's intentional because people use `/user` command to get the ai to write a message for them, and want to be able to regenerate that answer
