### ISSUE TITLE
Hang when load of lore file fails

### ISSUE THREAD

**Issue by kickahaota** [josephrocca/OpenCharacters#64]
I was trying out lore files, and thought I was being clever by saving the file to a local web server rather than messing around with a public host. Of course, I hadn't exposed that server to the Internet, so your server's attempt to load the lore file failed. But rather than displaying an error, OpenCharacters just hung at the "Downloading lore..." screen. It looks like ensureLoreUrlsAreLoaded isn't catching the exception.

![image](https://github.com/josephrocca/OpenCharacters/assets/39323419/b4810330-a202-4901-8fe6-7f841279db3e)

**Comment by josephrocca** [comment]
Thanks! Should at least show an alert/error popup now
