### ISSUE TITLE
[Enhancement] Zoom in mobile

### ISSUE THREAD

**Issue by augustobob** [josephrocca/OpenCharacters#67]
Hello, I would like to suggest an improvement in the use of the page. When I'm using it on my phone, the page zooms in on the text box, and it requires a pinch gesture to undo the zoom. It's possible to work around this behavior in several ways, as described on this page https://weblog.west-wind.com/posts/2023/Apr/17/Preventing-iOS-Safari-Textbox-Zooming . I hope you can consider my suggestion.

**Comment by josephrocca** [comment]
Thanks! Please let me know whether this is fixed - I don't have a safari device to test

**Comment by augustobob** [comment]
It's no longer zooming in the textbox, thanks for the quick improvement.
