### ISSUE TITLE
Feature Request: GPT-4 Turbo

### ISSUE THREAD

**Issue by tangodown18** [josephrocca/OpenCharacters#68]
Are you planning on adding GPT-4 Turbo (GPT-4-1106-preview) support on this or are you waiting for it to come out of preview?

**Comment by josephrocca** [comment]
Yep once it's stable and broadly available I will add (ping me). In the meantime you can add it manually in user settings like this:
```
{name:"gpt-3.5-turbo-16k", shortLabel:"gpt-3.5-turbo-16k - 4x longer memory", endpointUrl:"https://api.openai.com/v1/chat/completions", modelUrl:null, apiKey:"<OPENAI>", maxSequenceLength:16384, type:"chat-completion", tokenPricing:{prompt: 0.001, completion: 0.002}}
```
Just change the details there as appropriate and it should work.

**Comment by tangodown18** [comment]
Cool thank you for the help!
