### ISSUE TITLE
Issue with DaVinci: responses getting cut off.

### ISSUE THREAD

**Issue by RichWolfmann** [josephrocca/OpenCharacters#7]
I have been experiencing trouble while trying to use DaVinci. GPT works just fine, but whenever I switch to DaVinci, the completion shows up as incomplete, cut off. I'm suspecting it has something to do with max_tokens. I think adding more ways to tinker with the character, such as max_tokens, top P, top K or rep penalty would be quite good. What should I do to fix this in the meantime?

**Comment by josephrocca** [comment]
Thanks! This *should* be fixed now - please test and let me know if you're still running into this problem or any others.

I'll definitely be adding the ability to customize other params - tracking that here: https://github.com/josephrocca/OpenCharacters/issues/5

**Comment by RichWolfmann** [comment]
> Thanks! This _should_ be fixed now - please test and let me know if you're still running into this problem or any others.
> 
> I'll definitely be adding the ability to customize other params - tracking that here: #5

Thanks for the reply! Unfortunately I'm still running into the issue, maybe it's a problem on my end? A few days ago I was able to use DaVinci just fine but now I simply can't.

**Comment by josephrocca** [comment]
Hmm. Can you try clicking your browser refresh button a few times consecutively to trigger a cache clear? If it's still an issue, would you be able to post some screenshots and/or message sequence examples?

**Comment by josephrocca** [comment]
Actually I'm still seeing problems here myself... investigating

**Comment by RichWolfmann** [comment]
Sorry for the long delay, I've been busy. But the problem is fixed! I mus admit though, GPT is somehow better than DaVinci a lot of the time, way more customizable, so I'll stick to it.
