### ISSUE TITLE
My entire chat history and characters are suddenly gone.

### ISSUE THREAD

**Issue by RichWolfmann** [josephrocca/OpenCharacters#9]
I mostly use OpenCharacters from my phone, on the default Chrome browser. Everything was fine, I went to have lunch, and when I came back to keep chatting, I got an error message (can't really remember what it said). I refreshed the tab and now everything is gone. Is there any way to recover what I lost? This is extremely frustrating.

**Comment by josephrocca** [comment]
Hey Rich, very sorry about this!! But I'm hopeful that this is just a bug. I've just pushed some code which should make the bug's error message visible to you. Please refresh the page a few times to make sure your browser's page cache is cleared. Then copy/screenshot the error and paste here. Also, try clicking the export button and let me know if you get an error for that too.

**Comment by RichWolfmann** [comment]
Sorry, I've been gone for quite a bit, but it's fixed! Thank you! Everything went back to normal and I have all my convos and characters back.

**Comment by josephrocca** [comment]
Glad to hear! It's likely that it was just a UI bug (that I've since fixed) that was preventing the convo/character lists from rendering.
